### PR TITLE
more typography

### PR DESCRIPTION
**Pull request by PalmerAL**
add h3 + blockquotes

### CODE REVIEW

**Comment by nt1m** [comment]
Looks good, but is this from the md spec ?

**Comment by PalmerAL** [comment]
Maybe I'm just not looking hard enough, but I don't see anything in the
spec about either of these.

**Comment by nt1m** [comment]
@PalmerAL (This page)[http://www.google.com/design/spec/style/typography.html#typography-standard-styles] has all the styles, for the shade of blacks/whites and the font size.
There isn't a spec for blockquotes though, so anything that uses one of the defined shades is fine to me.

**Comment by PalmerAL** [comment]
Okay, I updated this to follow the spec styles for headlines.

**Pull request merged**
