### PR TITLE
Added callbacks for Dialogs

### PR DESCRIPTION
**Pull request by kCenk**

### CODE REVIEW

**Comment by nt1m** [comment]
I'd be nice if it could simply use events. I'm not a real fan of callbacks, especially with JS promises coming soon.

4 events could exist : "dismiss","close","confirm","open". Then the user could use addEventListener on the dialog element. There should probably be an emit function in the Material.prototype(); that could emit events I guess.

dismiss would be emitted when the user clicks cancel.
close would be emitted when the dialog is closed (by click cancel or confirm or by doing anything that will close it)
confirm would be emitted when the user clicks confirm.
open would be emitted when the user opens the dialog.

**Comment by kCenk** [comment]
As far as i can tell callbacks are supported in every browser, but custom events are hard to handle in ie and safari?

**Comment by nt1m** [comment]
@kCenk Latest Safari supports them (works on my iPad). IE has an alternative. I only plan supporting the 2 latest versions of each browser.

**Comment by nt1m** [comment]
Gonna merge for now, might as well switch to events in the future

**Pull request merged**
